apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cvat-dev-backend-server-hpa
  namespace: cvat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cvat-dev-backend-server
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cvat-dev-backend-utils-hpa
  namespace: cvat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cvat-dev-backend-utils
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cvat-dev-backend-worker-analyticsreports-hpa
  namespace: cvat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cvat-dev-backend-worker-analyticsreports
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cvat-dev-backend-worker-annotation-hpa
  namespace: cvat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cvat-dev-backend-worker-annotation
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cvat-dev-backend-worker-export-hpa
  namespace: cvat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cvat-dev-backend-worker-export
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cvat-dev-backend-worker-import-hpa
  namespace: cvat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cvat-dev-backend-worker-import
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cvat-dev-backend-worker-qualityreports-hpa
  namespace: cvat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cvat-dev-backend-worker-qualityreports
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cvat-dev-backend-worker-webhooks-hpa
  namespace: cvat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cvat-dev-backend-worker-webhooks
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cvat-dev-frontend-hpa
  namespace: cvat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cvat-dev-frontend
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: cvat-dev-grafana-hpa
  namespace: cvat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cvat-dev-grafana
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90