apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
    meta.helm.sh/release-name: cvat-dev
    meta.helm.sh/release-namespace: cvat
  labels:
    app.kubernetes.io/instance: cvat-dev-cvat
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-25.0.0
  name: cvat-dev-traefik
  namespace: cvat
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: web
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: websecure
  selector:
    app.kubernetes.io/instance: cvat-dev-cvat
    app.kubernetes.io/name: traefik
  sessionAffinity: None
  type: ClusterIP
