CREATE ROLE cvat_service WITH LOGIN PASSWORD 'REDACTED';

GRANT CONNECT ON DATABASE cvat TO cvat_service;

GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO cvat_service;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO cvat_service;

GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO cvat_service;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO cvat_service;
